Archiving 컴포넌트 구성 및 Project 페이지 구성
cau-likelion-org/cau-likelion-next pull request #13
Opened 2023-02-08 15:49 UTC by d0422

# 🛠️ 한 줄 요약

Archiving 컴포넌트 구성 및 Project 페이지 구성

## 상세

### 🔥 바꾼거

1. archiving 컴포넌트 tsconfig, nextconfig설정
2. archiving 컴포넌트 작성 - 헤더 컴포넌트,분류배열 인덱스별 카드뭉치 컴포넌트, 카드 컴포넌트 작성
3. IArchivingData, ProjectsArrayType request.d.ts로 이동
4. IProjectDetail(이전에 작성했던 인터페이스) IArchivingData를 상속하도록 변경
5. project 페이지 퍼블리싱
6. projectsSection api 작성

### 📢 같이 상의할 만한 것

data type에 대해

> projects, sessions, galleries API는 각각 기수, 트랙, 년도를 기준으로 객체 배열을 받습니다. 

>![image](https://user-images.githubusercontent.com/99241871/217578516-c468a0b6-0b78-4c7e-bc24-c92c3635ba30.png)

> 따라서 이 api 데이터들에 대해 컴포넌트를 최대한 재사용할 수 있도록 dev_stack과 description만 optional로 관리하도록 하였습니다.
> ![image](https://user-images.githubusercontent.com/99241871/217575327-df499e6e-6c24-4822-97d9-d2df4cec9596.png)
> 
> 이렇게 작성하면 모든 API에 대해 Object.entries로 key, value array를 통해 Archiving 컴포넌트를 사용가능하기에 이렇게 작성하였습니다.
> projectsSection의 경우 다음과 같이 사용할 수 있습니다.
> ![image](https://user-images.githubusercontent.com/99241871/217575725-795d0732-6fc7-4df9-a3ce-70db197c96ba.png)

혹시 이 외에 컴포넌트 재사용을 위한 다른 좋은 방법이 있으면 제시해주시면 감사하겠습니다.

## ✅ 작업리스트

- [x] archiving 컴포넌트 tsconfig, nextconfig 절대경로 설정
- [x] 헤더 컴포넌트 작성
- [x] 분류배열 인덱스별 카드뭉치 컴포넌트 작성 
- [x] key별 linkj, title 분기처리해주는 함수 작성
- [x] 카드 컴포넌트 작성 
- [x] IArchivingData, ProjectsArrayType request.d.ts로 이동
- [x] IProjectDetail(이전에 작성했던 인터페이스) IArchivingData를 상속하도록 변경
- [x] project 페이지 퍼블리싱
- [x] projectsSection api 작성

2023-02-09 13:25 UTC, yunseonyeong requested changes
아카이빙 컴포넌트 재사용가능하게 만들어주셔서 감사합니다 🙆🏻‍♀️
다만, 현재 Archiving 컴포넌트의 CardWrapper가 `justify-content: center` 속성을 가지고 있어
프로젝트 카드들이 좌측정렬이 되어있지 않습니다. 

그렇다고 flex-start 속성을 준다면, 화면 width에 따라서 우측 여백이 너무 커보이는 부작용이 있을 것 같아요.
그래서 다른 사이트들도 참고해보고 구글링도 해본 결과, grid를 도입했습니다. 

### Archiving.tsx
기존의 flexbox였던 CardWrapper를 grid로 바꿔주면서, 화면 width에 따라 1개, 2개, 3개로 정렬될 수 있도록 하였습니다.
```typescript

const CardWrapper = styled.div`
  display: grid;
  width: 100%;


  @media (min-width: 766px) and (max-width: 1123px){
    width: 75%;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
  }


  @media (min-width: 1124px) and (max-width: 1919px){
    width: 90%;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 20px
  }
  @media(min-width: 1920px){
    grid-template-columns: 1fr 1fr 1fr;
    gap: 20px;
  }

  @media (min-width: 360px) and (max-width: 765px){
    display: flex;
    flex-direction: column;
    gap: 20px;
    align-items: center;
    justify-content: center;
  }

  `;
```

### Card.tsx
기존에 Wrapper 컴포넌트에는 width, height 속성이 따로 없었는데, 화면 width가 커짐에 따라 카드의 크기는 변하지 않도록 고정하기 위해 픽셀로 고정해주었어요.
```typescript

const Wrapper = styled.div`
  border-radius: 25px;
  box-shadow: 10px 10px 50px rgba(68, 64, 105, 0.08);
  cursor: pointer;
  @media (min-width: 1920px) {
    width: 380px;
    height: 400px;
  }
  @media (min-width: 360px) and (max-width: 1919px){
    width: 330px;
    height: 370px;
  }
`;
const ImageWrapper = styled.div`
  position: relative;

  border-top-left-radius: 25px;
  border-top-right-radius: 25px;

  @media (min-width: 360px) and (max-width: 1919px){
    width: 330px;
    height: 200px;
  }
  @media (min-width: 1920px) {
    width: 380px;
    height: 250px;
  }
`;
const TextWrapper = styled.div`
  border-bottom-left-radius: 25px;
  border-bottom-right-radius: 25px;
  padding: 20px;

  @media (min-width: 360px) and (max-width: 1919px){
    width: 330px;
  }
  @media (min-width: 1920px) {
    width: 380px;
  }
`;
```

### LayoutArchiving.tsx
아카이빙 페이지들에 맞는 레이아웃을 따로 생성했습니다. 
기존에 Default 레이아웃의 좌우 여백값이 너무 커서, 카드를 3개 넣으면 초과되기 때문에 여백값을 줄였어요.
PageContainer 에 flex(column)속성과 align items center 속성을 줌으로써,
화면 크기가 줄어들었을 때 양옆으로 여백이 줄어들수있도록 했어요.
이건 모든 페이지 레이아웃에 필요한 부분인 것 같은데, 우선은 아카이빙에만 적용해보았습니다. 
그리고 내브바를 PageContainer 안쪽으로, 푸터는 바깥으로 뺐습니다 !

```typescript
const LayoutArchiving = ({ children }: { children: ReactElement; }) => {
  return (
    <>
      <PageContainer>
        <NavBar />
        <main>{children}</main>
      </PageContainer>
      <Footer isLandingLayout={false} />
    </>
  );
};

export default LayoutArchiving;

const PageContainer = styled.div`
  background-color: ${BackgroundColor};
  min-height: calc(100vh - 184px);
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;

  @media (max-width: 1440px) {
    padding: 100px 100px 100px 100px;
  }
  @media (max-width: 1280px) {
    padding: 100px 100px 100px 100px;
  }
  padding: 100px 160px 100px 160px;
`;

```
기존 내브바 padding이나 다른 페이지 레이아웃들도 조금씩 손봐야 모바일 뷰 대응시 편안할 것 같네요,,

2023-02-09 13:25 UTC, yunseonyeong commented on src/apis/project.ts
> +import { Res } from '@project/Projects/ProjectsSection';
Res type ProjectsSection에 없습니다. 확인 부탁드려요 !

2023-02-09 13:25 UTC, yunseonyeong commented on src/pages/project/index.tsx
아카이빙 모아보기 페이지들은 getStaticProps로 SSG 처리 해줘야 합니다! 저번에 설계회의때 말씀드린 것처럼, 초기 데이터는 SSG로 처리하고, 필터 검색 결과에 대해서는 react-query로 패칭해오는 방식으로 덮어 씌워야 할 것 같아요

2023-02-09 13:25 UTC, yunseonyeong commented on src/components/project/Projects/ProjectsSection.tsx
> +const ProjectsSection = () => {
SSG 처리하게 되면, project 데이터 섹션 컴포넌트로 넘겨받아서 디폴트 렌더링 해줘야 할 것 같슴다

2023-02-09 13:39 UTC, yunseonyeong commented on src/pages/project/index.tsx
아니 ㅡㅡ 이거 왜 여기로 잡혀있담

2023-02-09 18:50 UTC, d0422 commented on src/apis/project.ts
> +import { Res } from '@project/Projects/ProjectsSection';
ProjectsArrayType로 변경하였습니다!

2023-02-09 18:51 UTC, d0422 commented on src/pages/project/index.tsx
확인했습니다! SSG로 변경해볼게요!

2023-02-09 18:51 UTC, d0422 commented on src/components/project/Projects/ProjectsSection.tsx
> +const ProjectsSection = () => {
ProjectSection 컴포넌트에서 SSG처리하는건 불가능한가요?

2023-02-10 03:57 UTC, yunseonyeong commented on src/components/project/Projects/ProjectsSection.tsx
> +const ProjectsSection = () => {
넵 getStaticProps 호출은 페이지단위에서만 가능합니닷

2023-02-10 06:20 UTC, merged